slack:
  employee:
    before:
      days: 3
  customer:
    birthday:
      before:
        days: 7
    payment:
      pics:
        0:
          - https://i.imgur.com/Os451Qo.jpeg
          - https://i.imgur.com/unzfnaD.jpg
          - https://i.imgur.com/0gf5s.jpg
          - https://media.giphy.com/media/ND6xkVPaj8tHO/giphy.gif
          - https://media.giphy.com/media/DLxaEcISD5TaM/giphy.gif
        100000:
          - https://i.imgur.com/bDiTy7t.jpeg
          - https://i.imgur.com/3rYHhEu.jpg
          - https://i.imgur.com/gckZshj.jpg
          - https://media.giphy.com/media/G4qAZYIFr1Cww/giphy.gif
        1000000:
          - https://i.imgur.com/fj138M6.jpeg
          - https://i.imgur.com/ObVSUb6.jpg
          - https://i.imgur.com/EAFSXYp.png
          - https://i.imgur.com/uCKlPXG.jpg
          - https://i.imgur.com/zsxTYeC.jpg
          - https://media.giphy.com/media/cLLgfNJiKppgA/giphy.gif
          - https://media.giphy.com/media/w2JmkbOHFoq8U/giphy.gif
          - https://media.giphy.com/media/eDdEiM0Jq8Ene/giphy.gif
          - https://media.giphy.com/media/YBsd8wdchmxqg/giphy.gif