spring:
  datasource:
    url: ${DATABASE_URL}
report:
  parameters:
    customer-birthday:
      spreadsheet: ${CUSTOMER_BIRTHDAY_SPREADSHEET}
      cell-range: ${CUSTOMER_BIRTHDAY_CELL_RANGE}
    customer-debt:
      url: ${CUSTOMER_DEBT_JSON_URL}
    customer-payment:
      url: ${CUSTOMER_RECEIVABLE_JSON_URL}
    employee-event:
      url: ${EMPLOYEE_URL}
  schedule:
    CUSTOMER_BIRTHDAY: 0 0 9 * * *
    CUSTOMER_PAYMENT: 0 1 13 * * MON-FRI
    EMPLOYEE_EVENT: 0 0 9 * * *
  webhooks:
    CUSTOMER_BIRTHDAY: ${CUSTOMER_BIRTHDAY_SLACK_WEBHOOK}
    CUSTOMER_DEBT: ${CUSTOMER_DEBT_SLACK_WEBHOOK}
    CUSTOMER_PAYMENT: ${CUSTOMER_PAYMENT_SLACK_WEBHOOK}
    EMPLOYEE_EVENT: ${EMPLOYEE_SLACK_WEBHOOK}
google:
  spreadsheets:
    parameters:
      app.name: ${GOOGLE_APP_NAME}
      email: ${GOOGLE_APP_EMAIL}
      credentials: ${GOOGLE_CREDENTIALS_JSON}