report:
  schedule:
    CUSTOMER_BIRTHDAY: 0 * * * * *
    CUSTOMER_DEBT: 0 * * * * *
    CUSTOMER_PAYMENT: 0 * * * * *
    EMPLOYEE_EVENT: 0 * * * * *
  webhooks:
    PLAIN:
      CUSTOMER_BIRTHDAY: ${WEBHOOK_URL}
      CUSTOMER_DEBT: ${WEBHOOK_URL}
      CUSTOMER_PAYMENT: ${WEBHOOK_URL}
      EMPLOYEE_EVENT: ${WEBHOOK_URL}
