name: Manual deploy to Heroku

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to deploy"
        required: true
        type: string

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      branch: ${{ github.event.inputs.branch }}
    secrets: inherit
